### PR TITLE
(FM-7260) - Addition of support for ubuntu 18.04

### PR DESCRIPTION
**Pull request by david22swan**

### CODE REVIEW

**Comment by pmcmaw** [comment]
Is this also removal of Debian?

**Comment by david22swan** [comment]
@pmcmaw It's more along the lines of a cleanup. The module does not test against these OS and has not for some time from what I can gather.

**Comment by david22swan** [comment]
Removal and addition separated out into two different clearly labelled commits

**Comment by david22swan** [comment]
Removal commit separated out into separate PR:
https://github.com/puppetlabs/puppetlabs-ibm_installation_manager/pull/86

**Pull request merged**
