### PR TITLE
refactor ibm_pkg type

### PR DESCRIPTION
**Pull request by bmjen**
This PR includes a lot of the ibm_pkg provider refactoring done by @logicminds in #8 with some tweaks.

Requires #10

### CODE REVIEW

**Comment by logicminds** [comment]
yea, I still need to update my unit tests. I'll try and submit my tests by friday so we can get this moving.

**Comment by bmjen** [comment]
Thanks @logicminds . I'm doing a major overhaul of the ibm_installation_manager. So there will be a bit of a patch train developing here for a bit until I can ungate our internal CI setup. Any help you can provide on tests would be great!

Also... I plan on fixing the `puppet resource` functionality... as that's currently not working.

**Comment by logicminds** [comment]
@bmjen puppet resource works from my branch.

**Comment by logicminds** [comment]
also just remove ruby 1.8.7 as its not supported anymore.

**Comment by bmjen** [comment]
@logicminds do you mind pulling this PR and seeing where I possibly broke puppet resource?

Also.. I think I already removed ruby 1.8.7 in on of the PRs in this patch-train (which is getting increasingly large).

**Pull request merged**
